<?php

 module_load_include('inc', 'gainz', 'includes/forms');

function gainz_form_my_workout_set_node_form_alter(&$form, &$form_state, $form_id) {
    dsm($form);
    if(isset($_GET['workout']))
    {
        $form['field_my_nid']['und'][0]['value']['#default_value'] = $_GET['workout'];
        
    }
    //$form['field_my_nid']['#access'] = 0;
}

function gainz_menu() {
     $items['workouts/start/%/%/begin'] = array(
    'title' => 'Doing My Workout',
    'page callback' => '_gainz_begin_workout',
    'page arguments' => array(2,3),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function _gainz_begin_workout($user, $workoutSet) {
    
    $someStuff = 'Begin Workout for: ' . $workoutSet;
    
    $someStuff .= drupal_get_form('gainz_set_form');
    
    return $someStuff;
    
}